test: output correct test name in run_test_profile

diff --git a/test b/test
--- a/test
+++ b/test
@@ -3,7 +3,7 @@
 set -e
 
 run_test() {
-    test="$1" ; shift
+    local test="$1" ; shift
     case "$test" in
         test1) return 0 ;;
         test2) return 0 ;;
@@ -15,18 +15,19 @@ run_test() {
 }
 
 run_test_profile() {
+    local test="$1" ; shift
     local test_logs=".build/logs"
     [[ -d "$test_logs" ]] || mkdir -p "$test_logs"
     local test_passing="$test_logs/passing"
     local test_failing="$test_logs/failing"
     local exit_status='0'
     echo "running test '$test'" >&2
-    run_test "$@" || exit_status="$?"
+    run_test "$test" "$@" || exit_status="$?"
     echo "finished test '$test'" >&2
     if [[ "$exit_status" == '0' ]]; then
-        echo "$@" >> "$test_passing"
+        echo "$test" >> "$test_passing"
     else
-        echo "$@" >> "$test_failing"
+        echo "$test" >> "$test_failing"
     fi
     exit "$exit_status"
 }
